graph TD
    A[Input_Images_img_t_img_tm1_B_3_270_480] --> B[Concatenate_B_6_270_480]

    subgraph EarlyFusionEncoder
        B --> C[ConvGNAct_6_to_32_k7_s2]
        C --> D[Residual_32]
        D --> E[ConvGNAct_32_to_64_s2]
        E --> F[Residual_64]
        F --> G[ConvGNAct_64_to_128_s2]
        G --> H[Residual_128]
        H --> I[ConvGNAct_128_to_feat_dim_s2]
        I --> J[Projection_1x1_Conv_feat_dim]
        J --> K[Add_Vertical_Positional_Encoding]
        K --> L[Feature_Map_B_feat_dim+1_H16_W16]
    end

    subgraph AttentiveGRUDecoder
        L --> M[SpatialAttentionDecoder]
        M --> N[Initial_h_from_pooled_features]
        N --> O[GRUCell_Loop_pred_steps]
        O --> P[GRUCell_Input_prev_xy_context]
        P --> Q[GRUCell_Update_h]
        Q --> R[Output_Head_Predict_delta_xy]
        R --> S[Accumulate_Next_Position]
        S --> T{Teacher_Forcing?}
        T -->|Yes| U[Use_GT_prev_xy]
        T -->|No| V[Use_Predicted_prev_xy]
        U --> W[Loop_Back]
        V --> W
        W --> O
        O --> X[Predictions_B_pred_steps_2]
        M --> Y[Attention_Maps_per_step]
    end

    subgraph Auxiliary_Dynamics_Optional
        L --> Z[AdaptiveAvgPool2d_1x1]
        Z --> AA[Flatten]
        AA --> BB[Linear_feat_dim+1_to_128]
        BB --> CC[ReLU]
        CC --> DD[Linear_128_to_2]
        DD --> EE[Aux_Output_Speed_Accel]
    end

    X --> FF[Output_Predictions]
    Y --> GG[Output_Attention_Maps]
    EE --> HH[Output_Aux_Dynamics]